-- ============================================================
-- CivicTrust
-- 04_issue_lifecycle.sql
-- Issue Lifecycle Module
-- Version : 2.0 (Frozen)
-- ============================================================

-- ============================================================
-- DRAFT ISSUES
-- ============================================================

CREATE TABLE draft_issues (

    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    report_id UUID NOT NULL
        REFERENCES reports(id)
        ON DELETE CASCADE,

    ai_analysis_id UUID NOT NULL
        REFERENCES ai_analysis(id)
        ON DELETE CASCADE,

    suggested_category_id UUID
        REFERENCES categories(id),

    suggested_priority priority_type,

    -- NOTE: confidence_score intentionally excluded here.
    -- It already exists in ai_analysis. Access it via ai_analysis_id.

    officer_review_status review_status
        NOT NULL
        DEFAULT 'PENDING',

    review_comments TEXT,

    approved_by UUID
        REFERENCES users(id),

    approved_at TIMESTAMPTZ,

    rejection_reason TEXT,

    created_at TIMESTAMPTZ
        NOT NULL
        DEFAULT NOW(),

    updated_at TIMESTAMPTZ
        NOT NULL
        DEFAULT NOW(),

    CHECK (
        approved_at IS NULL
        OR approved_at >= created_at
    )

);

CREATE TRIGGER trg_draft_issues_updated
BEFORE UPDATE ON draft_issues
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

-- ============================================================
-- ISSUES
-- ============================================================

CREATE TABLE issues (

    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Human-readable ID e.g. CIV-2026-000001 (generated by backend)
    issue_number VARCHAR(30)
        UNIQUE
        NOT NULL,

    -- One draft maps to one issue (once approved)
    draft_issue_id UUID
        UNIQUE
        REFERENCES draft_issues(id),

    department_id UUID NOT NULL
        REFERENCES departments(id),

    category_id UUID NOT NULL
        REFERENCES categories(id),

    ward_id UUID NOT NULL
        REFERENCES wards(id),

    title VARCHAR(200)
        NOT NULL,

    description TEXT
        NOT NULL,

    priority priority_type
        NOT NULL,

    status issue_status
        NOT NULL
        DEFAULT 'OPEN',

    sla_rule_id UUID
        REFERENCES sla_rules(id),

    created_by UUID NOT NULL
        REFERENCES users(id),

    approved_by UUID
        REFERENCES users(id),

    approved_at TIMESTAMPTZ,

    resolved_at TIMESTAMPTZ,

    closed_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ
        NOT NULL
        DEFAULT NOW(),

    updated_at TIMESTAMPTZ
        NOT NULL
        DEFAULT NOW(),

    deleted_at TIMESTAMPTZ,

    -- Timestamp integrity checks
    CHECK (
        approved_at IS NULL
        OR approved_at >= created_at
    ),

    CHECK (
        resolved_at IS NULL
        OR (
            approved_at IS NOT NULL
            AND resolved_at >= approved_at
        )
    ),

    CHECK (
        closed_at IS NULL
        OR (
            resolved_at IS NOT NULL
            AND closed_at >= resolved_at
        )
    )

);

CREATE TRIGGER trg_issues_updated
BEFORE UPDATE ON issues
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

-- ============================================================
-- ISSUE REPORTS
-- Links reports to an official issue (many reports → one issue)
-- ============================================================

CREATE TABLE issue_reports (

    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    issue_id UUID NOT NULL
        REFERENCES issues(id)
        ON DELETE CASCADE,

    -- A report can only belong to one issue
    report_id UUID UNIQUE NOT NULL
        REFERENCES reports(id)
        ON DELETE CASCADE,

    linked_at TIMESTAMPTZ
        NOT NULL
        DEFAULT NOW()

);

-- ============================================================
-- MERGE RECORDS
-- Tracks when one issue is merged into another
-- ============================================================

CREATE TABLE merge_records (

    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    source_issue_id UUID NOT NULL
        REFERENCES issues(id),

    target_issue_id UUID NOT NULL
        REFERENCES issues(id),

    -- Prevents an issue being merged into itself
    CHECK (source_issue_id <> target_issue_id),

    merged_by UUID NOT NULL
        REFERENCES users(id),

    merge_reason TEXT,

    merged_at TIMESTAMPTZ
        NOT NULL
        DEFAULT NOW()

);

-- ============================================================
-- SPLIT RECORDS
-- Tracks when one issue is split into multiple child issues
-- ============================================================

CREATE TABLE split_records (

    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    parent_issue_id UUID NOT NULL
        REFERENCES issues(id),

    child_issue_id UUID NOT NULL
        REFERENCES issues(id),

    -- Prevents an issue being its own child
    CHECK (parent_issue_id <> child_issue_id),

    split_by UUID NOT NULL
        REFERENCES users(id),

    split_reason TEXT,

    split_at TIMESTAMPTZ
        NOT NULL
        DEFAULT NOW()

);

-- ============================================================
-- INDEXES
-- ============================================================

CREATE INDEX idx_draft_report
ON draft_issues(report_id);

CREATE INDEX idx_draft_ai
ON draft_issues(ai_analysis_id);

CREATE INDEX idx_draft_status
ON draft_issues(officer_review_status);

CREATE INDEX idx_draft_suggested_category
ON draft_issues(suggested_category_id);

CREATE INDEX idx_issue_number
ON issues(issue_number);

CREATE INDEX idx_issue_department
ON issues(department_id);

CREATE INDEX idx_issue_category
ON issues(category_id);

CREATE INDEX idx_issue_ward
ON issues(ward_id);

CREATE INDEX idx_issue_status
ON issues(status);

CREATE INDEX idx_issue_priority
ON issues(priority);

CREATE INDEX idx_issue_created_by
ON issues(created_by);

CREATE INDEX idx_issue_sla
ON issues(sla_rule_id);

CREATE INDEX idx_issue_reports_issue
ON issue_reports(issue_id);

CREATE INDEX idx_issue_reports_report
ON issue_reports(report_id);

CREATE INDEX idx_merge_source
ON merge_records(source_issue_id);

CREATE INDEX idx_merge_target
ON merge_records(target_issue_id);

CREATE INDEX idx_split_parent
ON split_records(parent_issue_id);

CREATE INDEX idx_split_child
ON split_records(child_issue_id);

-- ============================================================
-- MODULE COMPLETE
-- STATUS : FROZEN ✅
-- VERSION: 2.0
-- ============================================================